import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import RecoilContextProvider from './recoilcontextprovider'
export const metadata = {
  title: 'E-Commerce NextApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilContextProvider>{children}</RecoilContextProvider>
        </body>
    </html>
  )
}
